name: windows-msys2

on:
  workflow_dispatch:
  #push:
  #pull_request:

jobs:
  msys2:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        location: D:\
        update: true
        install: >-
          mingw-w64-i686-toolchain
          mingw-w64-i686-cmake
          mingw-w64-i686-clang-libs
          mingw-w64-i686-llvm-libs
          mingw-w64-i686-clang-tools-extra
          mingw-w64-i686-ninja
          mingw-w64-i686-python
          mingw-w64-i686-clang
          mingw-w64-i686-llvm
          base-devel
#          mingw-w64-i686-litehtml
     
    - name: Build
      shell: msys2 {0}
      run: |
        # Install Dependencies
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-base-5.15.16%2Bkde%2Br130-2-any.pkg.tar.zst
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-declarative-5.15.16%2Bkde%2Br22-1-any.pkg.tar.zst
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-imageformats-5.15.16-1-any.pkg.tar.zst
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-location-5.15.16%2Bkde%2Br7-1-any.pkg.tar.zst
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-multimedia-5.15.16-1-any.pkg.tar.zst
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-sensors-5.15.16-1-any.pkg.tar.zst
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-speech-5.15.16-1-any.pkg.tar.zst
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-svg-5.15.16%2Bkde%2Br5-1-any.pkg.tar.zst
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-tools-5.15.16-1-any.pkg.tar.zst
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-translations-5.15.16-1-any.pkg.tar.zst
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-webchannel-5.15.16%2Bkde%2Br3-1-any.pkg.tar.zst
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-qt5-winextras-5.15.16-1-any.pkg.tar.zst
        #wget -q https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-clang-14-14.0.6-1-any.pkg.tar.zst
        #wget -q https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-llvm-14-14.0.6-1-any.pkg.tar.zst
        pacman -U --noconfirm *.pkg.tar.zst
        
        cp -f psapi.h /mingw32/include/
        wget -q https://download.qt.io/archive/qtcreator/8.0/8.0.2/qt-creator-opensource-src-8.0.2.tar.gz
        tar xzf qt-creator-opensource-src-8.0.2.tar.gz
        cd qt-creator-opensource-src-8.0.2/
        
        # Patch
        cp -f ../clangformatbaseindenter.cpp ../clangformatutils.h ../clangformatutils.cpp src/plugins/clangformat/
        #sed -i '60 s/false/clang::format::FormatStyle::SortUsingDeclarationsOptions::SUD_Never/' src/plugins/clangformat/clangformatbaseindenter.cpp
        #sed -i '64 s/style.AlignTrailingComments = false;/style.AlignTrailingComments.Kind = clang::format::FormatStyle::TrailingCommentsAlignmentKinds::TCAS_Never;/' src/plugins/clangformat/clangformatbaseindenter.cpp
        #sed -i '77 s/startswith/starts_with/' src/plugins/clangformat/clangformatbaseindenter.cpp
        #sed -i '74 s/style.AlignTrailingComments = true;/style.AlignTrailingComments.Kind = FormatStyle::TrailingCommentsAlignmentKinds::TCAS_Always;/' src/plugins/clangformat/clangformatutils.cpp
        #sed -i '89 s/style.AlwaysBreakAfterReturnType = FormatStyle::RTBS_None;/style.BreakAfterReturnType = FormatStyle::ReturnTypeBreakingStyle::RTBS_Automatic;/' src/plugins/clangformat/clangformatutils.cpp
        #sed -i '91 s/style.AlwaysBreakTemplateDeclarations = FormatStyle::BTDS_Yes;/style.BreakTemplateDeclarations = FormatStyle::BreakTemplateDeclarationsStyle::BTDS_Yes;/' src/plugins/clangformat/clangformatutils.cpp
        #sed -i '121 s/style.ConstructorInitializerAllOnOneLineOrOnePerLine = false;//' src/plugins/clangformat/clangformatutils.cpp
        #sed -i '141 s/style.KeepEmptyLinesAtTheStartOfBlocks = false;//' src/plugins/clangformat/clangformatutils.cpp
        #sed -i '164 s/true/FormatStyle::SortUsingDeclarationsOptions::SUD_Lexicographic/' src/plugins/clangformat/clangformatutils.cpp
        #sed -i '169 s/style.SpaceInEmptyParentheses = false;//' src/plugins/clangformat/clangformatutils.cpp
        #sed -i '
        #rm -rf src/plugins/clangformat
        #cp -r ../clangformat src/plugins/
        #cp -rf ../libs src/
        
        MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
        cmake . -Wno-dev                              \
          -GNinja                               \
          -DCMAKE_INSTALL_PREFIX=/opt/qtcreator \
          -DWITH_DOCS=ON             \
          -DBUILD_DEVELOPER_DOCS=ON  \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_QBS=OFF            \
          -DPython3_EXECUTABLE=/mingw32/bin/python \
          -DWITH_TESTS=OFF           \
          -DCLANGTOOLING_LINK_CLANG_DYLIB=ON       
          #-DCMAKE_SHARED_LINKER_FLAGS=D:/msys64/mingw32/lib/libLLVM-19.dll.a
          #-DCMAKE_CXX_COMPILER=clang++             \
          #-DCMAKE_C_COMPILER=clang
        cmake --build . --parallel $(nproc)
        cmake --build . --target docs
        cmake --install .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: QtCreator
        path: D:\msys64\opt\qtcreator
