name: windows-msys2

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  msys2:
    runs-on: windows-latest

    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        location: D:\
        update: true
        install: >-
          mingw-w64-i686-toolchain
          mingw-w64-i686-cmake
          mingw-w64-i686-qt5-base
          mingw-w64-i686-qt5-svg
          mingw-w64-i686-qt5-tools
          mingw-w64-i686-qt5-speech
          mingw-w64-i686-qt5-sensors
          mingw-w64-i686-qt5-location
          mingw-w64-i686-qt5-winextras
          mingw-w64-i686-qt5-multimedia
          mingw-w64-i686-qt5-webchannel
          mingw-w64-i686-qt5-declarative
          mingw-w64-i686-qt5-imageformats
          mingw-w64-i686-qt5-translations
          mingw-w64-i686-clang-libs
          mingw-w64-i686-clang
          mingw-w64-i686-llvm
          mingw-w64-i686-llvm-libs
          mingw-w64-i686-clang-tools-extra
          mingw-w64-i686-ninja
          mingw-w64-i686-python
          mingw-w64-i686-litehtml
          base-devel
     
    - name: Build
      shell: msys2 {0}
      run: |
        wget -q https://download.qt.io/archive/qtcreator/8.0/8.0.2/qt-creator-opensource-src-8.0.2.tar.gz
        tar xzf qt-creator-opensource-src-8.0.2.tar.gz
        cd qt-creator-opensource-src-8.0.2/
        MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
        cmake . -Wno-dev                              \
          -GNinja                               \
          -DCMAKE_INSTALL_PREFIX=/opt/qtcreator \
          -DWITH_DOCS=ON             \
          -DBUILD_DEVELOPER_DOCS=ON  \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_QBS=OFF            \
          -DPython3_EXECUTABLE=/mingw32/bin/python \
          -DWITH_TESTS=OFF           \
          -DCLANGTOOLING_LINK_CLANG_DYLIB=ON
        cmake --build . --parallel $(nproc)
        cmake --build . --target docs
        cmake --install .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: QtCreator
        path: D:\msys64\opt\qtcreator
