name: windows-msys2

on:
  workflow_dispatch:

jobs:
  msys2:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        location: D:\
        update: true
        install: >-
          mingw-w64-i686-toolchain
          mingw-w64-i686-cmake
          mingw-w64-i686-clang-libs
          mingw-w64-i686-llvm-libs
          mingw-w64-i686-clang-tools-extra
          mingw-w64-i686-ninja
          mingw-w64-i686-python
          mingw-w64-i686-clang
          mingw-w64-i686-llvm
          base-devel
          #mingw-w64-x86_64-qt5-tools
     
    - name: Build
      shell: msys2 {0}
      run: |
        # Install Dependencies
        wget -q https://github.com/zxunge/mingw-package-archives/archive/refs/tags/v1.0.tar.gz
        tar xzf *.tar.gz
        pacman -U --noconfirm mingw-package-archives-1.0/*.pkg.tar.zst
        
        wget -q https://download.qt.io/archive/qtcreator/8.0/8.0.2/qt-creator-opensource-src-8.0.2.tar.gz
        tar xzf qt-creator-opensource-src-8.0.2.tar.gz
        cd qt-creator-opensource-src-8.0.2/
        
        # Patch
        cp -f ../psapi.h /mingw32/include/
        #cp -f ../CMakeLists.txt src/plugins/
        #cp -rf ../src ./
        cp -f ../src/plugins/clangformat/CMakeLists.txt ../src/plugins/clangformat/clangformatbaseindenter.cpp ../src/plugins/clangformat/clangformatutils.cpp src/plugins/clangformat/

        #export PATH=$PATH:/mingw64/bin
        cmake . -Wno-dev                        \
          -GNinja                               \
          -DCMAKE_INSTALL_PREFIX=/opt/qtcreator \
          -DWITH_DOCS=ON             \
          -DBUILD_DEVELOPER_DOCS=ON  \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_QBS=OFF            \
          -DPython3_EXECUTABLE=/mingw32/bin/python \
          -DWITH_TESTS=OFF           \
          -DCLANGTOOLING_LINK_CLANG_DYLIB=ON       
         
        cmake --build . --parallel $(nproc)
        #cmake --build . --target docs
        cmake --install .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: QtCreator
        path: D:\msys64\opt\qtcreator
