name: windows-msys2

on:
  workflow_dispatch:

jobs:
  msys2:
    runs-on: windows-latest

    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        location: D:\
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-qt5
          mingw-w64-x86_64-clang-libs
          mingw-w64-x86_64-llvm-libs
          mingw-w64-x86_64-clang-tools-extra
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-python
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-llvm
          base-devel
          p7zip

    - name: Checkout
      uses: actions/checkout@v4
     
    - name: Build
      id: build
      shell: msys2 {0}
      run: |
        TAG=8.0.2x64
        
        # Move files
        mkdir -p /opt/build
        mv * /opt/build/
        
        cd /opt/build/
        # Install Dependencies
        #wget -q https://github.com/zxunge/mingw-package-archives/archive/refs/tags/v1.0.tar.gz
        #tar xzf *.tar.gz
        #pacman -U --noconfirm mingw-package-archives-1.0/*.pkg.tar.zst
        
        wget -q https://download.qt.io/archive/qtcreator/8.0/8.0.2/qt-creator-opensource-src-8.0.2.tar.gz
        tar xzf qt-creator-opensource-src-8.0.2.tar.gz
        cd qt-creator-opensource-src-8.0.2/
        
        # Patch
        cp -f ../psapi.h /mingw64/include/
        #cp -f ../CMakeLists.txt src/plugins/
        #cp -rf ../src ./
        cp -f ../src/plugins/clangformat/CMakeLists.txt ../src/plugins/clangformat/clangformatbaseindenter.cpp ../src/plugins/clangformat/clangformatutils.cpp src/plugins/clangformat/
        cp -f ../src/libs/sqlite/sqlitebasestatement.h src/libs/sqlite/

        cmake . -Wno-dev                        \
          -GNinja                               \
          -DCMAKE_INSTALL_PREFIX=/opt/qtcreator \
          -DWITH_DOCS=ON             \
          -DBUILD_DEVELOPER_DOCS=ON  \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_QBS=OFF            \
          -DPython3_EXECUTABLE=/mingw64/bin/python \
          -DWITH_TESTS=OFF           \
          -DCLANGTOOLING_LINK_CLANG_DYLIB=ON       
         
        cmake --build . --parallel $(nproc)
        cmake --build . --target docs
        cmake --install .

        7zr a -mx9 -mqs=on -mmt=on /opt/qtcreator.7z /opt/qtcreator

        if [[ -v GITHUB_WORKFLOW ]]; then
            echo "RELEASE_TAG=${TAG}" >> $GITHUB_OUTPUT
        fi
         
    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
          allowUpdates: true
          tag: ${{ steps.build.outputs.RELEASE_TAG }}
          name: QtCreator
          artifacts: "D:/msys64/opt/qtcreator.7z"
          body: |
            This is QtCreator.
          token: ${{ secrets.GITHUB_TOKEN }}
